# Generated by Django 6.1.1 on 2026-10-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la categoría.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la categoría.')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está activa y visible en la tienda.')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto.', max_length=200)),
                ('marca', models.CharField(help_text='Marca del producto.', max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio del producto en la moneda local.', max_digits=12)),
                ('sku', models.CharField(help_text='Código único de identificación del producto (SKU).', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto.')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo y disponible para la venta.')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que el producto fue creado.')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del producto.')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto.', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.categoria')),
            ],
        ),
    ]
