# Generated by Django 6.1.1 on 2026-10-02 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el carrito.')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del carrito.')),
                ('usuario', models.OneToOneField(help_text='Usuario al que pertenece el carrito.', on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto en el carrito.')),
                ('agregado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se agregó el ítem al carrito.')),
                ('carro', models.ForeignKey(help_text='Carrito al que pertenece este ítem.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carro.carro')),
                ('producto', models.ForeignKey(help_text='Producto asociado a este ítem del carrito.', on_delete=django.db.models.deletion.CASCADE, related_name='items_carro', to='catalogo.producto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('carro', 'producto'), name='un_producto_por_carro')],
            },
        ),
    ]
